FROM alpine:latest

RUN mkdir -p /root/.pip && apk update \
    && apk upgrade \
    && apk add python \
    py2-pip \
    python2-dev \
    gcc \
    libc-dev \
    libffi-dev \
    openssl-dev \
    make \
    jpeg-dev \
    curl

ADD conf/pipconf /root/.pip/pip.conf

RUN pip install fluidasserts
