# Imagen base de linux RedHat 
FROM ubuntu:14.04

# Dudas sobre la imagen en cuestion
MAINTAINER FLUID Engineering Team <engineering@fluid.la>

ENV DEBIAN_FRONTEND noninteractive      # instalación no interactiva
ENV USER root

# Instala SSH, Python y SUDO para administracion por Ansible

