= Prevenir Inyección SQL: Lenguaje SCALA
:lang:		es
:author:	Juan Pablo Tamayo 
:email:		jtamayo@fluid.la 
:date: 	    	2015/12/24
:language:	java
:imagesdir:	./images
:revnumber:	v1.0
:revdate:	{date}
:revmark:	Versión inicial

== Necesidad

Prevenir inyección SQL usando sentencias parametrizadas.

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente
solución tiene sentido:

. Se esta desarrollando una aplicación en lenguaje de programación
Scala^v2.10.4^. 
. La aplicación utiliza una base de datos relacional.

== Solución 

Si una aplicación requiere que un cliente ingrese un dato como un usuario,
contraseña, correo, ID o cualquier tipo de información sensible y este valor
del dato es pasado directamente como parte de una sentencia SQL, es posible
hacer inyecciones con instrucciones SQL a la sentencia para obtener más
información de la tabla o de la base de datos.

Dependiendo directamente en la entrada del usuario se pueden causar resultados
inesperados.

Cuando diseñamos sentencias para MySQL tenemos que asegurar que la información
suministrada por el usuario es validada con unas reglas predefinidas y
transformarla a una sentencia parametrizada.

Ejemplo:

[source]
----
val selectStatement = "SELECT * FROM test_t WHERE id =? "; // <1>
val prepStmt = conn.prepareStatement(selectStatement);     // <2>
prepStmt.setInt(1, 1);                                     // <3> 
val rs = prepStmt.executeQuery();                          // <4>
----
<1> Especificar el formato de la consulta SQL
<2> Precompilar la consulta indicada
<3> Agregar los parámetros definidos para la sentencia
<4> Ejecutar la consulta precompilada con los parametros indicados

== Referencias 

. REQ. 0164 Debe usarse construcciones parametrizadas o procedimientos
almacenados parametrizados para la creación dinámica de sentencias

include::include/footer.adoc[]
